import {classifyCombination,beatsCombination} from './casino-games.mjs';

export const CASINO_VISUAL_CSS=`
.hkm-casino-visual{--card-w:72px;--card-h:102px;--reel-h:112px;position:relative;isolation:isolate;min-height:354px;border:4px solid #6b482c;border-radius:48% 48% 20px 20px/12% 12% 20px 20px;background:radial-gradient(ellipse at 50% 35%,#235f46 0%,#133e2f 60%,#08291e 100%);box-shadow:inset 0 0 0 2px #ad8950,inset 0 0 55px #0007,0 9px 20px #0004;overflow:hidden;padding:20px 18px 18px;color:#f5ebca}
.hkm-casino-visual::before{content:'';position:absolute;inset:7px;border:1px solid #d9c17436;border-radius:inherit;pointer-events:none;background-image:repeating-linear-gradient(35deg,transparent 0 3px,#ffffff02 3px 4px);z-index:-1}
.hkm-table-mark{position:absolute;left:50%;top:44%;transform:translate(-50%,-50%);width:80%;text-align:center;pointer-events:none;color:#dbc98c28;font-weight:900;letter-spacing:.17em;font-size:clamp(21px,5vw,38px)}
.hkm-table-mark small{display:block;font-size:11px;letter-spacing:.25em}
.hkm-table-status{display:flex;justify-content:center;align-items:center;gap:8px;min-height:32px;text-align:center;margin:7px 0;font-size:13px;position:relative;z-index:2}
.hkm-table-badge{display:inline-flex;align-items:center;gap:5px;border:1px solid #dec0807a;border-radius:20px;background:#08291ece;padding:4px 11px;color:#f8e9b4;font-size:12px;white-space:nowrap}
.hkm-table-result{position:relative;z-index:3;border:1px solid #dcbd74;border-radius:6px;padding:10px 14px;margin:12px auto 0;max-width:620px;background:#122119ed;color:#f6e3ad;text-align:center;font-weight:650;box-shadow:0 3px 10px #0003}
.hkm-table-result.is-revealing{animation:hkm-result-in .4s both;animation-delay:var(--reveal-delay,0ms)}
.hkm-card-row{display:flex;align-items:center;justify-content:center;gap:9px;min-height:var(--card-h);position:relative;z-index:1}
.hkm-playing-card{width:var(--card-w);height:var(--card-h);flex:0 0 var(--card-w);position:relative;perspective:650px;filter:drop-shadow(1px 4px 3px #0005);color:#20252a;vertical-align:middle}
.hkm-card-flipper{position:absolute;inset:0;transform-style:preserve-3d;transform:rotateY(0deg)}
.hkm-playing-card.is-back .hkm-card-flipper{transform:rotateY(180deg)}
.hkm-card-front,.hkm-card-back{position:absolute;inset:0;border-radius:7px;backface-visibility:hidden;overflow:hidden}
.hkm-card-front{background:linear-gradient(120deg,#fffdf7,#f0eee4);border:1px solid #e5dbc1;box-shadow:inset 0 0 0 2px #fff7;color:#25252a}
.hkm-playing-card.is-red .hkm-card-front{color:#bb3039}
.hkm-card-back{transform:rotateY(180deg);border:3px solid #f7efd9;background:repeating-linear-gradient(45deg,#274977 0 3px,#25416a 3px 6px);box-shadow:inset 0 0 0 1px #cdd8eb,inset 0 0 0 5px #153056}
.hkm-card-back::before{content:'';position:absolute;inset:11%;border:1px solid #b3c6e67d;border-radius:50%;background:repeating-conic-gradient(from 45deg,#afc4e333 0 45deg,transparent 45deg 90deg);transform:rotate(20deg)}
.hkm-card-back::after{content:'✦';position:absolute;inset:0;display:grid;place-items:center;font-size:30px;color:#d9e1eb}
.hkm-card-corner{position:absolute;left:5px;top:4px;font:700 17px/1.0 Georgia,serif;text-align:center;z-index:2}
.hkm-card-corner span{display:block;font-size:15px;line-height:1.1}
.hkm-card-corner.is-bottom{left:auto;top:auto;right:5px;bottom:4px;transform:rotate(180deg)}
.hkm-card-pips{position:absolute;inset:22% 25%;font:22px/1 Georgia,serif}.hkm-card-pips span{position:absolute;left:var(--pip-x);top:var(--pip-y);transform:translate(-50%,-50%) rotate(var(--pip-angle,0deg))}
.hkm-card-pips.is-single{font-size:42px}
.hkm-card-court{position:absolute;left:21%;top:20%;width:58%;height:61%;fill:currentColor;color:inherit}
.hkm-card-joker{position:absolute;inset:24% 15%;display:grid;place-items:center;font-size:30px;color:#303849}
.hkm-card-joker small{font:700 9px/1.2 system-ui;letter-spacing:.04em}
.hkm-card-deal{animation:hkm-card-deal .38s cubic-bezier(.2,.8,.2,1) both;animation-delay:var(--deal-delay,0ms)}
.hkm-playing-card.is-flipping .hkm-card-flipper{animation:hkm-card-flip .48s ease both;animation-delay:var(--deal-delay,0ms)}
.hkm-bj-zone{text-align:center;position:relative;z-index:1}
.hkm-bj-zone .hkm-table-status{margin:0 0 9px}.hkm-bj-player .hkm-table-status{margin:10px 0 0}
.hkm-bj-player{margin-top:46px}.hkm-bj-opponent .hkm-card-row{min-height:104px}
.hkm-bj-player .hkm-casino-hand{display:flex;justify-content:center;flex-wrap:wrap;gap:9px;min-height:var(--card-h)}
.hkm-bj-score{display:inline-grid;place-items:center;width:32px;height:32px;border-radius:50%;border:1px solid #e1c486;background:#0b281e;font-weight:800;font-size:15px;color:#ffe9b0}
.hkm-bj-score.is-bust{color:#ffaaa7;border-color:#ed8c7b}
.hkm-chip-pot{display:flex;align-items:center;justify-content:center;gap:9px;position:relative;z-index:1;margin:7px auto;color:#ebdfba;font-size:12px}
.hkm-chip-stack{position:relative;width:43px;height:36px;flex:0 0 43px}.hkm-table-chip{display:grid;place-items:center;position:absolute;left:0;width:42px;height:29px;border:4px dashed #d7dfed;border-radius:50%;background:#244e94;color:#fff;font:bold 10px/1 system-ui;box-shadow:0 2px 0 #11294d,0 3px 4px #0006;bottom:var(--chip-y,0px)}
.hkm-table-chip.is-gold{background:#ac7731;border-color:#f3deb3;box-shadow:0 2px 0 #62451f,0 3px 4px #0006}
.hkm-dd-table{min-height:425px;border-radius:24px;padding-top:16px}
.hkm-dd-seats{display:flex;justify-content:space-between;align-items:flex-start;gap:10px;position:relative;z-index:1}
.hkm-dd-opponent{display:grid;grid-template-columns:38px 1fr;gap:6px;align-items:center;font-size:12px;max-width:44%}
.hkm-dd-opponent[data-player='2']{grid-template-columns:1fr 38px;text-align:right}.hkm-dd-opponent[data-player='2'] .hkm-dd-avatar{order:2}.hkm-dd-opponent[data-player='2'] .hkm-dd-seathand{order:3;grid-column:1/-1;margin-left:auto}
.hkm-dd-avatar{width:36px;height:36px;border:1px solid #d0b377;border-radius:50%;background:linear-gradient(145deg,#c1ad74,#57523c);display:grid;place-items:center;color:#25291f;font-size:18px;box-shadow:0 2px 8px #0004}
.hkm-dd-seatname{font-weight:700;white-space:normal}.hkm-dd-seatcount{display:block;color:#d0d8c2;font-size:11px;font-weight:400}
.hkm-dd-seathand{grid-column:1/-1;height:61px;position:relative;width:80px;margin-top:4px;--card-w:34px;--card-h:49px}
.hkm-dd-seathand .hkm-playing-card{position:absolute;top:0;left:var(--back-x);transform:rotate(var(--back-angle));transform-origin:50% 100%;filter:drop-shadow(1px 2px 2px #0004)}
.hkm-dd-seathand .hkm-card-back{border-width:2px}.hkm-dd-seathand .hkm-card-back::after{font-size:18px}
.hkm-dd-bottom{position:absolute;top:14px;left:50%;transform:translateX(-50%);text-align:center;--card-w:28px;--card-h:40px;font-size:10px;color:#d4ddc4}
.hkm-dd-bottom .hkm-card-row{gap:4px;min-height:40px}.hkm-dd-bottom .hkm-card-corner{font-size:10px;top:2px;left:2px}.hkm-dd-bottom .hkm-card-corner span{font-size:9px}.hkm-dd-bottom .hkm-card-corner.is-bottom{right:2px;bottom:2px;left:auto;top:auto}.hkm-dd-bottom .hkm-card-pips{font-size:10px}.hkm-dd-bottom .hkm-card-pips.is-single{font-size:18px}.hkm-dd-bottom .hkm-card-joker{font-size:14px}.hkm-dd-bottom .hkm-card-joker small{display:none}
.hkm-dd-play{min-height:104px;display:flex;flex-direction:column;align-items:center;justify-content:center;margin:1px 0 4px;position:relative;z-index:2;--card-w:49px;--card-h:69px}
.hkm-dd-play .hkm-card-row{width:100%;gap:0;min-height:69px;padding:0 20px}.hkm-dd-play .hkm-playing-card+.hkm-playing-card{margin-left:clamp(-37px,-3vw,-17px)}
.hkm-dd-play .hkm-card-corner{font-size:12px;left:3px;top:3px}.hkm-dd-play .hkm-card-corner span{font-size:11px}.hkm-dd-play .hkm-card-corner.is-bottom{left:auto;top:auto;right:3px;bottom:3px}.hkm-dd-play .hkm-card-pips{font-size:15px}.hkm-dd-play .hkm-card-pips.is-single{font-size:28px}.hkm-dd-play .hkm-card-joker{font-size:20px}.hkm-dd-play .hkm-card-joker small{font-size:7px}
.hkm-dd-playlabel{font-size:12px;color:#e5d29c;min-height:22px;margin-bottom:6px;text-align:center}.hkm-dd-empty{color:#e3d29a;letter-spacing:.05em;font-size:13px}
.hkm-dd-player{position:relative;z-index:3;margin-top:6px}.hkm-dd-player .hkm-table-status{margin:0 0 8px}.hkm-dd-fan-window{width:100%;overflow-x:auto;overflow-y:hidden;overscroll-behavior-x:contain;touch-action:pan-x;scrollbar-color:#b49960 #0c2d21;scrollbar-width:thin}
.hkm-dd-fan{height:136px;position:relative;width:100%;max-width:790px;margin:0 auto;padding-top:27px;display:block!important;--card-w:65px;--card-h:94px}
.hkm-casino .hkm-dd-fan button.hkm-playing-card{padding:0;min-height:0;max-width:none;width:calc((100% - 24px - var(--card-w)) / max(1,var(--fan-count) - 1));background:none;border:0;border-radius:7px;position:absolute;left:calc(12px + var(--fan-index) * (100% - 24px - var(--card-w)) / max(1,var(--fan-count) - 1));top:28px;transform:translateY(var(--fan-raise,0px));transition:transform .16s ease,filter .16s ease;box-shadow:none;opacity:1;z-index:var(--fan-index);cursor:pointer}
.hkm-casino .hkm-dd-fan button.hkm-playing-card:last-child{width:var(--card-w)}.hkm-dd-fan .hkm-card-flipper{width:var(--card-w);pointer-events:none;transform:rotate(var(--fan-angle,0deg));transform-origin:50% 110%}
.hkm-casino .hkm-dd-fan button.hkm-playing-card[aria-pressed=true]{--fan-raise:-22px;filter:drop-shadow(0 0 3px #ffe49f) drop-shadow(1px 3px 2px #0007);z-index:calc(30 + var(--fan-index));color:inherit}
.hkm-casino .hkm-dd-fan button.hkm-playing-card:hover:not(:disabled){--fan-raise:-12px;background:none}.hkm-casino .hkm-dd-fan button.hkm-playing-card[aria-pressed=true]:hover{--fan-raise:-22px}
.hkm-casino .hkm-dd-fan button.hkm-playing-card:disabled{opacity:1;cursor:default}.hkm-dd-fan .hkm-card-corner.is-bottom{display:none}.hkm-dd-fan .hkm-card-corner{left:4px}.hkm-dd-fan .hkm-card-corner span{font-size:14px}.hkm-dd-fan .hkm-card-pips{font-size:20px}
.hkm-dd-fan .hkm-card-flipper.is-dealing{animation:hkm-fan-deal .35s ease-out both;animation-delay:var(--deal-delay)}
.hkm-dd-fan:empty{height:44px}
.hkm-dd-selection{min-height:25px;color:#e4d29a;font-size:12px;text-align:center;padding:2px 5px}.hkm-dd-selection.is-invalid{color:#ffb3aa}
.hkm-slot-machine{min-height:366px;border-radius:18px;background:linear-gradient(135deg,#202737,#131820);border-color:#ae8551;padding:20px 28px 18px;box-shadow:inset 0 0 0 2px #eed49c,inset 0 0 45px #0008,0 8px 20px #0005}
.hkm-slot-marquee{text-align:center;border:2px solid #b38849;border-radius:40px 40px 9px 9px;padding:9px;background:linear-gradient(#482b3b,#261d2b);font-weight:900;font-size:25px;letter-spacing:.14em;color:#ffe1a4;text-shadow:0 0 10px #f7bd4a8a;box-shadow:inset 0 0 0 3px #e7bd681c;margin-bottom:17px}
.hkm-slot-window{display:flex;gap:7px;position:relative;padding:8px;border:3px solid #9c743e;border-radius:11px;background:#10131b;box-shadow:inset 0 0 0 2px #f0d7a02b,0 2px 12px #000a;max-width:560px;margin:auto}
.hkm-slot-window::after{content:'';position:absolute;inset:8px;border-top:1px solid #ffce7940;border-bottom:1px solid #ffce7940;pointer-events:none;box-shadow:inset 0 24px 18px -18px #191627c9,inset 0 -24px 18px -18px #191627c9;z-index:2}
.hkm-slot-reel{position:relative;flex:1;height:var(--reel-h);overflow:hidden;background:linear-gradient(#d2d5d0,#fffff5 40%,#fffff5 60%,#c6c7c0);border:1px solid #f7e4b7;border-radius:4px;box-shadow:inset 0 1px 9px #0005}
.hkm-slot-strip{position:absolute;top:0;left:0;width:100%;transform:translateY(var(--slot-end))}.hkm-slot-symbol{display:grid;place-items:center;height:var(--reel-h);font-size:clamp(35px,6.4vw,67px);font-weight:900;font-family:"Segoe UI Emoji","Apple Color Emoji",system-ui;color:#b72d30;text-shadow:0 2px 0 #fffc;line-height:1}
.hkm-slot-reel.is-spinning .hkm-slot-strip{animation:hkm-slot-spin var(--spin-duration) cubic-bezier(.12,.6,.15,1) both}
.hkm-slot-reel.is-winner{box-shadow:inset 0 0 0 2px #efd06b,0 0 14px #f2c3656e}.hkm-slot-payline{position:absolute;left:-10px;right:-10px;top:50%;border-top:2px solid #f5d27b99;pointer-events:none;z-index:3}.hkm-slot-payline::before,.hkm-slot-payline::after{content:'▶';position:absolute;color:#f9d990;left:-3px;top:-13px;font-size:17px}.hkm-slot-payline::after{left:auto;right:-3px;content:'◀'}
.hkm-slot-machine[data-animating=true] .hkm-slot-reel.is-winner{box-shadow:inset 0 1px 9px #0005}
.hkm-slot-footer{display:flex;align-items:center;justify-content:center;gap:10px;margin-top:16px}.hkm-slot-light{width:8px;height:8px;border-radius:50%;background:#ffe1a1;box-shadow:0 0 9px #f8c660}.hkm-slot-machine[data-animating=true] .hkm-slot-light{animation:hkm-slot-light .5s alternate 4}.hkm-slot-payouts{display:flex;justify-content:center;gap:18px;font-size:11px;color:#d4bd91;margin-top:12px}
.hkm-lottery-desk{min-height:368px;border-radius:19px;background:radial-gradient(ellipse at 50% 30%,#293854,#111b2b 70%);border-color:#9b8058;padding:19px 26px}.hkm-lottery-title{text-align:center;font-size:21px;color:#f5deb1;letter-spacing:.14em;margin-bottom:12px;font-weight:850}
.hkm-lottery-ticket{position:relative;max-width:440px;margin:0 auto 20px;background:linear-gradient(115deg,#fff4d2,#ebdfbc);color:#2e3744;border-radius:6px;padding:15px 18px 13px;box-shadow:0 7px 16px #0005;border:1px solid #f2d7a0;overflow:hidden}
.hkm-lottery-ticket::before,.hkm-lottery-ticket::after{content:'';position:absolute;top:58%;width:20px;height:20px;border-radius:50%;background:#19253a;left:-11px;box-shadow:inset -1px 0 1px #0004}.hkm-lottery-ticket::after{left:auto;right:-11px}
.hkm-lottery-tickethead{display:flex;justify-content:space-between;align-items:center;font-size:10px;letter-spacing:.06em;border-bottom:1px dashed #9b977f;padding-bottom:7px;margin-bottom:8px}.hkm-lottery-tickethead strong{font-size:14px}.hkm-lottery-ticketnumber{display:flex;justify-content:center;gap:16px;font:900 42px/1.3 Georgia,serif;letter-spacing:.08em;color:#253755}.hkm-lottery-ticketfoot{display:flex;justify-content:space-between;margin-top:9px;border-top:1px dashed #9b977f;padding-top:8px;font-size:10px}.hkm-lottery-barcode{height:16px;width:79px;display:inline-block;background:repeating-linear-gradient(90deg,#253755 0 2px,transparent 2px 4px,#253755 4px 5px,transparent 5px 8px)}
.hkm-lottery-drawlabel{text-align:center;font-size:12px;color:#d2d8e4;letter-spacing:.1em;margin:5px 0 12px}.hkm-lottery-balls{display:flex;gap:15px;justify-content:center;align-items:center;min-height:65px;perspective:700px}.hkm-lottery-ball{display:grid;place-items:center;width:61px;height:61px;border-radius:50%;background:radial-gradient(circle at 32% 25%,#fff7db,#e7b862 60%,#8b5f2b 100%);box-shadow:inset -2px -4px 6px #82522270,0 4px 9px #0005;border:1px solid #e3c388;color:#293447;font:900 28px/1 Georgia,serif}.hkm-lottery-ball span{display:grid;place-items:center;width:35px;height:35px;border-radius:50%;background:#fff8e8e3;border:1px solid #f7e4c7}
.hkm-lottery-ball.is-matched{background:radial-gradient(circle at 32% 25%,#e8ffed,#63ae8b 60%,#235240);border-color:#badcbd}.hkm-lottery-ball.is-revealing{animation:hkm-ball-reveal .5s both;animation-delay:var(--ball-delay)}
.hkm-casino-idle{min-height:265px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;text-align:center;background:radial-gradient(ellipse,#20533c,#103127);border:3px solid #755233;border-radius:14px;color:#efe2bc}.hkm-casino-idle .hkm-card-row{--card-w:60px;--card-h:85px;gap:0}.hkm-casino-idle .hkm-playing-card{transform:rotate(var(--idle-angle));margin-left:-12px}.hkm-casino-idle strong{font-size:18px;letter-spacing:.05em}.hkm-casino-idle p{margin:0;font-size:12px;color:#cbd7c4}
@keyframes hkm-card-deal{from{opacity:0;transform:translate(60px,-45px) rotate(12deg) scale(.85)}to{opacity:1;transform:none}}
@keyframes hkm-card-flip{0%{transform:rotateY(180deg)}100%{transform:rotateY(0deg)}}
@keyframes hkm-fan-deal{from{opacity:0;transform:translate(35px,-30px) scale(.85) rotate(var(--fan-angle,0deg))}to{opacity:1;transform:rotate(var(--fan-angle,0deg))}}
@keyframes hkm-slot-spin{0%{transform:translateY(0)}85%{filter:blur(1px)}100%{transform:translateY(var(--slot-end));filter:none}}
@keyframes hkm-ball-reveal{0%{opacity:0;transform:translateY(-25px) rotateY(180deg) scale(.5)}65%{opacity:1;transform:translateY(6px) rotateY(0) scale(1.04)}100%{opacity:1;transform:none}}
@keyframes hkm-result-in{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}
@keyframes hkm-slot-light{from{opacity:.25}to{opacity:1}}
@media(max-width:600px){.hkm-casino-visual{--card-w:58px;--card-h:84px;padding:15px 10px;min-height:323px;border-width:3px}.hkm-card-corner{font-size:15px;left:4px;top:3px}.hkm-card-corner span{font-size:13px}.hkm-card-corner.is-bottom{right:4px;bottom:3px}.hkm-card-pips{font-size:17px}.hkm-card-pips.is-single{font-size:32px}.hkm-card-row{gap:6px}.hkm-bj-opponent .hkm-card-row{min-height:84px}.hkm-bj-player{margin-top:43px}.hkm-dd-table{min-height:397px;padding:14px 8px 9px}.hkm-dd-fan{--card-w:48px;--card-h:81px;height:122px}.hkm-dd-fan .hkm-card-corner{font-size:13px;left:3px;top:3px}.hkm-dd-fan .hkm-card-corner span{font-size:12px}.hkm-dd-fan .hkm-card-pips{font-size:15px}.hkm-dd-opponent{font-size:10px;gap:4px;grid-template-columns:29px 1fr;max-width:39%}.hkm-dd-opponent[data-player='2']{grid-template-columns:1fr 29px}.hkm-dd-avatar{height:28px;width:28px;font-size:15px}.hkm-dd-seatcount{font-size:10px}.hkm-dd-bottom{top:13px;--card-w:23px;--card-h:33px}.hkm-dd-bottom .hkm-card-row{gap:2px;min-height:33px}.hkm-dd-seathand{height:53px;width:64px;--card-w:28px;--card-h:41px}.hkm-dd-play{--card-w:39px;--card-h:56px;min-height:95px;margin-top:8px}.hkm-dd-play .hkm-card-row{min-height:56px;padding:0 8px}.hkm-dd-play .hkm-playing-card+.hkm-playing-card{margin-left:clamp(-34px,-5vw,-14px)}.hkm-slot-machine{--reel-h:88px;min-height:335px;padding:17px 13px}.hkm-slot-marquee{font-size:21px}.hkm-slot-window{gap:5px;padding:6px}.hkm-slot-symbol{font-size:43px}.hkm-slot-payouts{gap:11px;font-size:10px}.hkm-lottery-desk{min-height:354px;padding:17px 13px}.hkm-lottery-title{font-size:19px}.hkm-lottery-ticket{padding:13px 14px}.hkm-lottery-ticketnumber{font-size:37px}.hkm-lottery-balls{gap:11px}.hkm-lottery-ball{height:55px;width:55px;font-size:26px}.hkm-lottery-ball span{width:32px;height:32px}.hkm-table-result{font-size:12px;padding:9px;margin-top:10px}}
@media(max-width:350px){.hkm-dd-fan{--card-w:43px;--card-h:77px}.hkm-dd-fan .hkm-card-corner{left:2px;font-size:12px}.hkm-dd-fan .hkm-card-corner span{font-size:11px}.hkm-dd-opponent{max-width:38%;grid-template-columns:25px 1fr}.hkm-dd-opponent[data-player='2']{grid-template-columns:1fr 25px}.hkm-dd-avatar{width:24px;height:24px}.hkm-dd-bottom{--card-w:20px;--card-h:29px;top:17px}.hkm-dd-play .hkm-playing-card+.hkm-playing-card{margin-left:-25px}.hkm-slot-symbol{font-size:37px}.hkm-slot-payouts{gap:7px}.hkm-table-badge{padding:4px 8px;font-size:11px}.hkm-lottery-tickethead{font-size:9px}.hkm-lottery-tickethead strong{font-size:12px}}
@media(max-width:600px){.hkm-dd-fan{width:max(100%,calc((var(--fan-count) - 1) * 30px + var(--card-w) + 24px));max-width:none}.hkm-dd-fan-window{border-bottom:1px solid #b6a46b35}}
@media(prefers-reduced-motion:reduce){.hkm-casino-visual *{animation:none!important;transition:none!important}}
`;

const RANKS={11:'J',12:'Q',13:'K',14:'A',15:'2',16:'小王',17:'大王'};
const SYMBOLS=['🍒','🍋','🔔','⭐','💎','7'];
const score=cards=>{let n=0,a=0;for(const c of cards){if(c.rank===14){n+=11;a++;}else n+=c.rank===15?2:Math.min(10,c.rank);}while(n>21&&a-->0)n-=10;return n;};

export function suggestCasinoCards(game){
 if(game?.type!=='doudizhu'||game.stage!=='playing')return [];
 const groups=new Map();for(const c of game.hands[0]){if(!groups.has(c.rank))groups.set(c.rank,[]);groups.get(c.rank).push(c);}
 const target=game.lastPlay?.combo||null,out=new Map(),add=cards=>{const combo=classifyCombination(cards,target)||classifyCombination(cards);if(combo&&beatsCombination(combo,target))out.set(cards.map(c=>c.id).sort().join(','),{cards,combo});};
 for(const [rank,same]of groups){for(let n=1;n<=Math.min(4,same.length);n++)add(same.slice(0,n));if(same.length>=3)for(const [r,wing]of groups)if(r!==rank){add([...same.slice(0,3),wing[0]]);if(wing.length>=2)add([...same.slice(0,3),...wing.slice(0,2)]);}if(same.length===4){const remaining=game.hands[0].filter(c=>c.rank!==rank);if(remaining.length>=2)add([...same,...remaining.slice(0,2)]);const pairs=[...groups].filter(([r,w])=>r!==rank&&w.length>=2).map(([,w])=>w.slice(0,2));if(pairs.length>=2)add([...same,...pairs[0],...pairs[1]]);}}
 if(groups.has(16)&&groups.has(17))add([groups.get(16)[0],groups.get(17)[0]]);
 for(const [size,min]of [[1,5],[2,3],[3,2]])for(let start=3;start<=14;start++){const main=[],ranks=[];for(let r=start;r<=14&&groups.get(r)?.length>=size;r++){main.push(...groups.get(r).slice(0,size));ranks.push(r);if(ranks.length<min)continue;add([...main]);if(size===3){const rest=game.hands[0].filter(c=>!ranks.includes(c.rank));if(rest.length>=ranks.length)add([...main,...rest.slice(0,ranks.length)]);const pairs=[...groups].filter(([p,w])=>!ranks.includes(p)&&w.length>=2).map(([,w])=>w.slice(0,2));if(pairs.length>=ranks.length)add([...main,...pairs.slice(0,ranks.length).flat()]);}}}
 const candidates=[...out.values()];candidates.sort((a,b)=>target?((a.combo.kind==='rocket'?2:a.combo.kind==='bomb'?1:0)-(b.combo.kind==='rocket'?2:b.combo.kind==='bomb'?1:0)||a.combo.high-b.combo.high):b.cards.length-a.cards.length||a.combo.high-b.combo.high);
 return candidates[0]?.cards.map(c=>c.id)||[];
}

export function createCasinoVisuals({window,document}){
 const mount=document.createElement('div');mount.className='hkm-casino-visual-mount';
 let signature='',last=null,table=null,selectionNote=null,pendingUid=null,animationTimer=null,disposed=false;
 const el=(tag,text,className)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(className)n.className=className;return n;};
 const reduced=()=>window.matchMedia?.('(prefers-reduced-motion: reduce)').matches===true;
 function card(data,{back=false,button=false,delay=null,flip=false}={}){
  const n=el(button?'button':'div',undefined,'hkm-playing-card'+(back?' is-back':'')+(/[♥♦]/.test(data?.label)?' is-red':'')+(delay!==null&&!reduced()?' hkm-card-deal':'')+(flip&&!reduced()?' is-flipping':''));
  if(button){n.type='button';n.setAttribute('aria-pressed','false');}n.dataset.cardId=data?.id||'back';n.setAttribute('aria-label',back?'暗牌':data.label);if(delay!==null)n.style.setProperty('--deal-delay',delay+'ms');
  const flipper=el('div',undefined,'hkm-card-flipper'),front=el('div',undefined,'hkm-card-front'),rear=el('div',undefined,'hkm-card-back');flipper.setAttribute('aria-hidden','true');
  const rank=RANKS[data?.rank]||String(data?.rank||''),suit=data?.label?.match(/[♠♥♣♦]/)?.[0]||'';
  for(const bottom of [false,true]){const corner=el('div',rank,'hkm-card-corner'+(bottom?' is-bottom':''));corner.append(el('span',suit));front.append(corner);}
  if(data?.rank>=16){const j=el('div','♜','hkm-card-joker');j.append(el('small',rank));front.append(j);}
  else if(data?.rank>=11&&data.rank<=13){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 50 76');svg.classList.add('hkm-card-court');const shapes=[['path',{d:'M4 6H46V70H4Z',fill:'none',stroke:'currentColor','stroke-width':'1'}],['path',{d:'M15 25L10 11L20 16L25 6L30 16L40 11L35 25Z',fill:'#bd9348',stroke:'currentColor','stroke-width':'1.4'}],['circle',{cx:'25',cy:'33',r:'9',fill:'#e7c895',stroke:'currentColor','stroke-width':'1'}],['path',{d:'M9 66L13 46L25 42L37 46L41 66Z'}],['path',{d:'M25 45L19 65H31Z',fill:'#bd9348'}],['path',{d:'M9 68L41 8',fill:'none',stroke:'#bd9348','stroke-width':'2'}]];if(data.rank===12)shapes.push(['path',{d:'M17 34Q25 48 33 34L35 47L15 47Z',fill:'#bd9348'}]);for(const [tag,attrs]of shapes){const s=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attrs))s.setAttribute(k,v);svg.append(s);}front.append(svg);}
  else{const count=data?.rank===14?1:data?.rank===15?2:data?.rank||1,pips=el('div',undefined,'hkm-card-pips'+(count===1?' is-single':''));const places=count===1?[[50,50]]:count===2?[[50,0],[50,100]]:count===3?[[50,0],[50,50],[50,100]]:count<=5?[[0,0],[100,0],[0,100],[100,100],...(count===5?[[50,50]]:[])]:count<=8?[[0,0],[100,0],[0,50],[100,50],[0,100],[100,100],...(count===7?[[50,25]]:count===8?[[50,25],[50,75]]:[])]:[[0,0],[100,0],[0,33],[100,33],[0,67],[100,67],[0,100],[100,100],...(count===9?[[50,50]]:[[50,17],[50,83]])];for(const [x,y]of places){const pip=el('span',suit);pip.style.setProperty('--pip-x',x+'%');pip.style.setProperty('--pip-y',y+'%');if(y>50)pip.style.setProperty('--pip-angle','180deg');pips.append(pip);}front.append(pips);}
  flipper.append(front,rear);n.append(flipper);return n;
 }
 function chipPot(stake,total=stake){const pot=el('div',undefined,'hkm-chip-pot'),stack=el('div',undefined,'hkm-chip-stack');for(let i=0;i<Math.min(5,Math.max(2,Math.ceil(stake/20)));i++){const chip=el('span',String(stake),'hkm-table-chip'+(stake>=50?' is-gold':''));chip.style.setProperty('--chip-y',i*3+'px');stack.append(chip);}pot.append(stack,el('span',total===stake?'下注 '+stake+'筹码':'底池 '+total+'筹码'));return pot;}
 function result(game,delay=0){if(game.stage!=='done')return;const n=el('div',game.resultText,'hkm-table-result'+(delay&&!reduced()?' is-revealing':''));n.setAttribute('role','status');n.style.setProperty('--reveal-delay',delay+'ms');table.append(n);}
 function badge(text){return el('span',text,'hkm-table-badge');}
 function blackjack(game,hand,animate,previous){
  table.classList.add('hkm-bj-table');const mark=el('div','BLACKJACK','hkm-table-mark');mark.append(el('small','21 · 对手17点停牌'));table.append(mark);
  const opponent=el('div',undefined,'hkm-bj-zone hkm-bj-opponent'),dealerTitle=el('div',undefined,'hkm-table-status');dealerTitle.append(badge('对手玩家'),el('span',game.stage==='done'?score(game.opponent):'?', 'hkm-bj-score'+(score(game.opponent)>21&&game.stage==='done'?' is-bust':'')));opponent.append(dealerTitle);
  const dealerCards=el('div',undefined,'hkm-card-row');for(let i=0;i<game.opponent.length;i++){const hidden=game.stage==='playing'&&i===1,old=previous?.opponent?.some(c=>c.id===game.opponent[i].id),initial=animate&&!previous,flip=animate&&previous?.stage==='playing'&&game.stage==='done'&&i===1;dealerCards.append(card(game.opponent[i],{back:hidden,delay:initial?(i===0?120:360):animate&&!old?250+(i-2)*180:null,flip}));}opponent.append(dealerCards);
  const player=el('div',undefined,'hkm-bj-zone hkm-bj-player');hand.className='hkm-casino-hand';hand.replaceChildren();for(let i=0;i<game.hand.length;i++){const fresh=!previous?.hand?.some(c=>c.id===game.hand[i].id);hand.append(card(game.hand[i],{delay:animate&&fresh?(!previous?i*240:0):null}));}const ownTitle=el('div',undefined,'hkm-table-status');ownTitle.append(badge('你的手牌'),el('span',score(game.hand),'hkm-bj-score'+(score(game.hand)>21?' is-bust':'')));player.append(hand,ownTitle);table.append(opponent,chipPot(game.stake),player);result(game,animate?Math.max(450,(game.opponent.length-1)*180+250):0);return animate?Math.max(800,(game.opponent.length-1)*180+750):0;
 }
 function dou(game,hand,animate,previous,onSelect){
  table.classList.add('hkm-dd-table');const seats=el('div',undefined,'hkm-dd-seats');for(const p of [1,2]){const seat=el('div',undefined,'hkm-dd-opponent');seat.dataset.player=String(p);seat.dataset.remaining=String(game.hands[p].length);const name=el('div','对手玩家'+(p===1?'甲':'乙'),'hkm-dd-seatname');name.append(el('span','农民 · '+game.hands[p].length+'张','hkm-dd-seatcount'));seat.append(el('div',p===1?'♠':'♣','hkm-dd-avatar'),name);const backs=el('div',undefined,'hkm-dd-seathand');backs.setAttribute('aria-label',game.hands[p].length+'张背牌');for(let i=0;i<Math.min(5,game.hands[p].length);i++){const b=card({id:'opponent-'+p+'-'+i,rank:14,label:'♠A'},{back:true});b.style.setProperty('--back-x',i*9+'px');b.style.setProperty('--back-angle',(-12+i*6)+'deg');backs.append(b);}seat.append(backs);seats.append(seat);}table.append(seats);
  const bottom=el('div',undefined,'hkm-dd-bottom'),bottomCards=el('div',undefined,'hkm-card-row');game.bottom.forEach(c=>bottomCards.append(card(c)));bottom.append(bottomCards,el('span','地主底牌'));table.append(bottom);
  const playArea=el('div',undefined,'hkm-dd-play');if(game.lastPlay){const played=game.lastPlay,playLabel=el('div',(played.player===0?'你':played.player===1?'对手玩家甲':'对手玩家乙')+' · '+played.combo.name,'hkm-dd-playlabel'),row=el('div',undefined,'hkm-card-row');playArea.dataset.player=String(played.player);playArea.dataset.combination=played.combo.kind;const fresh=JSON.stringify(played)!==JSON.stringify(previous?.lastPlay);played.cards.forEach((c,i)=>row.append(card(c,{delay:animate&&fresh?i*35:null})));playArea.append(playLabel,row);}else playArea.append(el('div',game.stage==='playing'?'本轮由你先出':'对局结束','hkm-dd-empty'));table.append(playArea,chipPot(game.stake,game.stake*3));
  const own=el('div',undefined,'hkm-dd-player'),status=el('div',undefined,'hkm-table-status');status.append(badge('你 · 地主 · '+game.hands[0].length+'张'),badge(game.stage==='playing'?'轮到你出牌':'本局结束'));own.append(status);hand.className='hkm-casino-hand hkm-dd-fan';hand.style.setProperty('--fan-count',String(game.hands[0].length));hand.replaceChildren();game.hands[0].forEach((c,i)=>{const b=card(c,{button:true});b.dataset.selectable=String(game.stage==='playing');b.style.setProperty('--fan-index',String(i));b.style.setProperty('--fan-angle',((i-(game.hands[0].length-1)/2)*.55)+'deg');if(animate&&!previous){b.style.setProperty('--deal-delay',i*25+'ms');b.querySelector('.hkm-card-flipper').classList.add('is-dealing');}b.addEventListener('click',()=>onSelect(c.id));hand.append(b);});selectionNote=el('div','选择手牌后出牌，或点击提示。','hkm-dd-selection');const fanWindow=el('div',undefined,'hkm-dd-fan-window');fanWindow.append(hand);own.append(fanWindow,selectionNote);table.append(own);result(game,animate?350:0);return animate?1250:0;
 }
 function slots(game,animate){
  table.classList.add('hkm-slot-machine');table.append(el('div','LUCKY 7','hkm-slot-marquee'));const reels=el('div',undefined,'hkm-slot-window');reels.append(el('div',undefined,'hkm-slot-payline'));game.reels.forEach((symbol,i)=>{const reel=el('div',undefined,'hkm-slot-reel'+(animate?' is-spinning':'')+(new Set(game.reels).size<3?' is-winner':''));reel.dataset.symbol=symbol;reel.setAttribute('aria-label','转轮'+(i+1)+'：'+symbol);const strip=el('div',undefined,'hkm-slot-strip'),rows=animate?[...Array.from({length:24+i*6},(_,j)=>SYMBOLS[(j+i)%6]),symbol]:[symbol];for(const s of rows)strip.append(el('div',s,'hkm-slot-symbol'));strip.style.setProperty('--slot-end','calc(var(--reel-h) * -'+(rows.length-1)+')');reel.style.setProperty('--spin-duration',(1200+i*350)+'ms');reel.append(strip);reels.append(reel);});table.append(reels);const footer=el('div',undefined,'hkm-slot-footer');footer.append(el('span',undefined,'hkm-slot-light'),chipPot(game.stake),el('span',undefined,'hkm-slot-light'));table.append(footer);const prizes=el('div',undefined,'hkm-slot-payouts');prizes.append(el('span','三同 ×8'),el('span','两同 返还本金'),el('span','六种图案 · 三个转轮'));table.append(prizes);result(game,animate?2000:0);return animate?2400:0;
 }
 function lottery(game,animate){
  table.classList.add('hkm-lottery-desk');table.append(el('div','哈基米幸运彩','hkm-lottery-title'));const ticket=el('div',undefined,'hkm-lottery-ticket');ticket.dataset.ticket=game.ticket;const header=el('div',undefined,'hkm-lottery-tickethead');header.append(el('strong','幸运三位数'),el('span','系统发行 · 本局票券'));const numbers=el('div',undefined,'hkm-lottery-ticketnumber');for(const n of game.ticket)numbers.append(el('span',n));const foot=el('div',undefined,'hkm-lottery-ticketfoot');foot.append(el('span','票面 '+game.stake+'筹码'),el('span',undefined,'hkm-lottery-barcode'));ticket.append(header,numbers,foot);table.append(ticket,el('div','本期开奖','hkm-lottery-drawlabel'));const balls=el('div',undefined,'hkm-lottery-balls');for(let i=0;i<3;i++){const ball=el('div',undefined,'hkm-lottery-ball'+(animate?' is-revealing':'')+(game.ticket[i]===game.draw[i]?' is-matched':''));ball.dataset.digit=game.draw[i];ball.dataset.position=String(i);ball.style.setProperty('--ball-delay',(350+i*450)+'ms');ball.append(el('span',game.draw[i]));balls.append(ball);}table.append(balls);result(game,animate?1700:0);return animate?2150:0;
 }
 function updateSelection(game,selected){if(!table||game?.type!=='doudizhu')return;for(const b of table.querySelectorAll('.hkm-casino-hand button'))b.setAttribute('aria-pressed',String(selected.has(b.dataset.cardId)));if(!selectionNote)return;if(game.stage==='done'){selectionNote.classList.remove('is-invalid');selectionNote.textContent='本局已结束。';return;}const cards=game.hands[0].filter(c=>selected.has(c.id)),combo=classifyCombination(cards,game.lastPlay?.combo)||classifyCombination(cards),valid=combo&&beatsCombination(combo,game.lastPlay?.combo);selectionNote.classList.toggle('is-invalid',cards.length>0&&!valid);selectionNote.textContent=!cards.length?'选择手牌后出牌，或点击提示。':!combo?'已选'+cards.length+'张 · 不能组成有效牌型':combo.name+' · '+cards.length+'张'+(valid?' · 可以出牌':' · 不能压过上一手');}
 function render({active,hand,selectedCards,onSelect}){
  if(disposed)return;const game=active?.game;if(!game){reset();const idle=el('div',undefined,'hkm-casino-idle'),row=el('div',undefined,'hkm-card-row');for(const [i,c]of [{id:'demo-S14',rank:14,label:'♠A'},{id:'demo-H13',rank:13,label:'♥K'},{id:'demo-D12',rank:12,label:'♦Q'}].entries()){const n=card(c);n.style.setProperty('--idle-angle',(-15+i*15)+'deg');row.append(n);}idle.append(row,el('strong','哈基米系统赌场'),el('p','选择牌桌、转轮或彩票，开始一局。'));mount.replaceChildren(idle);return;}
  const nextSignature=JSON.stringify([active.uid,game.type,game.stage,game.hand,game.opponent,game.hands,game.bottom,game.lastPlay,game.reels,game.ticket,game.draw,game.resultText]);if(nextSignature===signature){updateSelection(game,selectedCards);return;}
  const previous=last?.uid===active.uid?last.game:null,animate=!reduced()&&(pendingUid===active.uid||previous!==null);pendingUid=null;if(animationTimer!==null)window.clearTimeout(animationTimer);animationTimer=null;table=el('div',undefined,'hkm-casino-visual');table.dataset.game=game.type;table.dataset.match=active.uid;table.dataset.animating='false';table.dataset.stage=game.stage;selectionNote=null;mount.replaceChildren(table);
  let duration=0;if(game.type==='blackjack')duration=blackjack(game,hand,animate,previous);else if(game.type==='doudizhu')duration=dou(game,hand,animate,previous,onSelect);else if(game.type==='slots')duration=slots(game,animate);else if(game.type==='lottery')duration=lottery(game,animate);
  signature=nextSignature;last={uid:active.uid,game:JSON.parse(JSON.stringify(game))};updateSelection(game,selectedCards);if(duration){table.dataset.animating='true';const owned=table;animationTimer=window.setTimeout(()=>{if(table===owned)owned.dataset.animating='false';animationTimer=null;},duration);}
 }
 function reset(){if(animationTimer!==null)window.clearTimeout(animationTimer);animationTimer=null;signature='';last=null;table=null;selectionNote=null;pendingUid=null;mount.replaceChildren();}
 return {mount,render,updateSelection,announce:uid=>{pendingUid=uid;},reset,dispose(){disposed=true;reset();mount.remove();}};
}
